name: Go Bench

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  Bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Run Benchmark
      run: go test -bench . -benchmem -benchtime 5s ./... | tee benchmark.txt

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: benchmark.txt
        github-token: ${{ secrets.GHBOT_TOKEN }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@lemon-mint'
        gh-repository: 'github.com/lemon-mint/hsq-benchmark-results'
